// All 58 Algerian Wilayas (states) for the order form dropdown
export const algerianStates = [
  { value: "01", label: "Adrar - أدرار" },
  { value: "02", label: "Chlef - الشلف" },
  { value: "03", label: "Laghouat - الأغواط" },
  { value: "04", label: "Oum El Bouaghi - أم البواقي" },
  { value: "05", label: "Batna - باتنة" },
  { value: "06", label: "Béjaïa - بجاية" },
  { value: "07", label: "Biskra - بسكرة" },
  { value: "08", label: "Béchar - بشار" },
  { value: "09", label: "Blida - البليدة" },
  { value: "10", label: "Bouira - البويرة" },
  { value: "11", label: "Tamanrasset - تمنراست" },
  { value: "12", label: "Tébessa - تبسة" },
  { value: "13", label: "Tlemcen - تلمسان" },
  { value: "14", label: "Tiaret - تيارت" },
  { value: "15", label: "Tizi Ouzou - تيزي وزو" },
  { value: "16", label: "Alger - الجزائر" },
  { value: "17", label: "Djelfa - الجلفة" },
  { value: "18", label: "Jijel - جيجل" },
  { value: "19", label: "Sétif - سطيف" },
  { value: "20", label: "Saïda - سعيدة" },
  { value: "21", label: "Skikda - سكيكدة" },
  { value: "22", label: "Sidi Bel Abbès - سيدي بلعباس" },
  { value: "23", label: "Annaba - عنابة" },
  { value: "24", label: "Guelma - قالمة" },
  { value: "25", label: "Constantine - قسنطينة" },
  { value: "26", label: "Médéa - المدية" },
  { value: "27", label: "Mostaganem - مستغانم" },
  { value: "28", label: "M'sila - المسيلة" },
  { value: "29", label: "Mascara - معسكر" },
  { value: "30", label: "Ouargla - ورقلة" },
  { value: "31", label: "Oran - وهران" },
  { value: "32", label: "El Bayadh - البيض" },
  { value: "33", label: "Illizi - إليزي" },
  { value: "34", label: "Bordj Bou Arréridj - برج بوعريريج" },
  { value: "35", label: "Boumerdès - بومرداس" },
  { value: "36", label: "El Tarf - الطارف" },
  { value: "37", label: "Tindouf - تندوف" },
  { value: "38", label: "Tissemsilt - تيسمسيلت" },
  { value: "39", label: "El Oued - الوادي" },
  { value: "40", label: "Khenchela - خنشلة" },
  { value: "41", label: "Souk Ahras - سوق أهراس" },
  { value: "42", label: "Tipaza - تيبازة" },
  { value: "43", label: "Mila - ميلة" },
  { value: "44", label: "Aïn Defla - عين الدفلى" },
  { value: "45", label: "Naâma - النعامة" },
  { value: "46", label: "Aïn Témouchent - عين تموشنت" },
  { value: "47", label: "Ghardaïa - غرداية" },
  { value: "48", label: "Relizane - غليزان" },
  { value: "49", label: "El M'Ghair - المغير" },
  { value: "50", label: "El Meniaa - المنيعة" },
  { value: "51", label: "Ouled Djellal - أولاد جلال" },
  { value: "52", label: "Bordj Badji Mokhtar - برج باجي مختار" },
  { value: "53", label: "Béni Abbès - بني عباس" },
  { value: "54", label: "Timimoun - تيميمون" },
  { value: "55", label: "Touggourt - تقرت" },
  { value: "56", label: "Djanet - جانت" },
  { value: "57", label: "In Salah - عين صالح" },
  { value: "58", label: "In Guezzam - عين قزام" },
];
